### ISSUE TITLE
brand as DaFoDiL a.k.a. "Daffodil"

### ISSUE THREAD

**Issue by dwhieb** [digitallinguistics/spec#129]
**Da**ta **Fo**rmat for **Di**gital **L**inguistics

**Comment by dwhieb** [comment]
This was actually handled in 695420657fffb9039b3bdcbaa125efaae952756b.

**Comment by dwhieb** [comment]
This wasn't done in all relevant places. I think the readme needs updating again.

**Comment by vadekh** [comment]
It looks to me like the README.md in ./github is up to date, but the normal README.md just needs this line added to its introduction: `This repository contains the specification for the Data Format for Digital Linguistics (abbreviated as DaFoDiL, i.e. Daffodil). `
