### ISSUE TITLE
support word templates and template slots

### ISSUE THREAD

**Issue by dwhieb** [digitallinguistics/spec#265]
Create a schema for a word template, which includes:
- [x] name of the template
- [x] list of slots
- [x] name of each slot
- [x] whether each slot is optional

Lexemes should have a field called `slot`, whose value must be `template:slot`, indicating the applicable template and the slot that the lexeme fills in it.

**Comment by vadekh** [comment]
@dwhieb I will get on this early this week. Just to clarify, this is a template for Lexeme objects? Also how should we indicate what language and lexical category a template belongs to? Would it be a list under some aspect of Language?

**Comment by dwhieb** [comment]
Oh good questions. Honestly hadn't thought about that yet. Yes, it seems like word templates belong to languages, so maybe we should have a `Language.templates` property. 

Indicating the lexical category for a template is a great idea. `WordTemplate.category` would be good for that I think.

So `Lexeme.slot` needs to indicate a template slot. Since a Lexeme already has information about lexical category, then `Lexeme.slot` doesn't need to indicate the word template, just the slot. It should probably be the value of `WordTemplate.slots.abbreviation`.
