### ISSUE TITLE
allow Translation to be an object or string

### ISSUE THREAD

**Issue by dwhieb** [digitallinguistics/spec#297]
## Description

The Translation schema should support either an object or a string. If the Translation is a string, it is assumed to be English.

Check out the MultiLangString schema for a model of how the schema should look.

**Comment by vadekh** [comment]
I'd call this a minor version change, correct?

**Comment by dwhieb** [comment]
Right! For both the Translation scheme and the overall spec (though I’ll bump the version on the spec myself).
