### ISSUE TITLE
v1.0.0

### ISSUE THREAD

**Issue by dwhieb** [digitallinguistics/spec#376]
- [x] update package version
- [x] create release notes
- [x] finalize version numbers of schemas
- [x] publish release
- [x] delete release notes from repo
- [x] improve blog post
- [x] improve user documentation based on blog post
- [x] publish blog post ([here](https://medium.com/digital-linguistics/dlx-data-format-v1-0-0-4692305c9f6e))
- [x] disseminate blog post (see below)

# Dissemination
- [x] Algonquian Components team
- [x] social media
- [x] UCSB linguistics
- [x] professional network
- [x] AILLA
- [ ] Linguist List
- [ ] departmental talks (U Chicago, UCSB)
- [ ] ICLDC talk
- [ ] LD&D article
- [ ] LD&C article

**Comment by dwhieb** [comment]
@Calvin1119 @vadekh Could you guys give these [draft release notes](https://github.com/digitallinguistics/spec/blob/master/.github/RELEASE_NOTES.md) for v1.0.0 a quick once-over and let me know if anything is confusing, incorrect, inconsistent, or could be improved? Thanks!

**Comment by vadekh** [comment]
@dwhieb Those look fine to me! Everything is consistent, and straightforward, particularly the breaking changes that a user might need to notice.
