### ISSUE TITLE
add Glottolog's AES to the Language.status schema

### ISSUE THREAD

**Issue by xrotwang** [digitallinguistics/spec#379]
Glottolog's [Agglomerated Endangerment Status](https://glottolog.org/langdoc/status) could be added to the status schema.

**Comment by dwhieb** [comment]
Great suggestion, thank you!

@vadekh Since you worked on the Status field, would you like to implement this?

While we're at it, let's also improve the documentation of this schema a bit by adding links to more information about each scale in the description of each of the fields.
