### ISSUE TITLE
Orthography: writingSystem

### ISSUE THREAD

**Issue by HughP** [digitallinguistics/spec#389]
In reading over the schema. Two things stick out:

1. There is no notion of a writing system. - there is an orthography, but orthographies and writing systems are different.
2. There doesn't appear to be a way to describe an event.

**Comment by dwhieb** [comment]
> 1. There is no notion of a writing system. - there is an orthography, but orthographies and writing systems are different.

That's correct. So far there hasn't been a use case for a writing system (/script) schema, just an orthography schema. By orthography, I mean a set of conventions for writing a particular language in a particular writing system / script.

However, I see now that the Orthography schema doesn't have a field for specifying the writing system it uses. It seems like a `writingSystem` property, whose value is an [ISO 15924 script code](https://en.wikipedia.org/wiki/ISO_15924), would be useful. What do you think?

> 2. There doesn't appear to be a way to describe an event.

Can you clarify what type of event you mean? Do you have in mind something like a fieldwork session?

**Comment by HughP** [comment]
Yes on both accounts. I came here after reading on imdi which has sessions
as a type of event.

An orthography is the matching of sounds to characters. And also has a list
of rules for spelling in a language.

A script is a list of characters.

A writing system is the application of characters in a script in a
particular manner. So don’t conflate writing system and script.

Spot on. Keep up the good work.

**Comment by dwhieb** [comment]
Thanks @HughP! Renaming this issue to focus on writing systems and opening a new one for events/sessions.

**Comment by dwhieb** [comment]
@vadekh Could you implement an `Orthography.writingSystem` property, whose value is an [ISO 15924 script code](https://en.wikipedia.org/wiki/ISO_15924)? The description can be really straightforward: "The writing system used by this orthography. Should be a valid 4-letter [ISO 15924 script code](https://en.wikipedia.org/wiki/ISO_15924)."

**Comment by dwhieb** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[spec] Orthography.writingSystem](https://trello.com/c/PUnSRrHe/89-spec-orthographywritingsystem)

**Comment by HughP** [comment]
FYI: The following linked paper would be a great resource to consult on this issue as it clearly outlines the conceptual relationships between a script, an orthography, a writing system, and a language. 

I have re-drawn the main graphical figure in Peter's paper and included it here as a PDF.
[ScriptCommnet.pdf](https://github.com/digitallinguistics/spec/files/5544686/ScriptCommnet.pdf)
Constable, Peter G. 2002. Toward a Model for Language Identification Defining an ontology of language-related categories. SIL Electronic Working Papers 2002-003. 1–45. Dallas, Texas: SIL International. https://www.sil.org/resources/publications/entry/7853

**Comment by dwhieb** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[format] review: Orthography.writingSystem](https://trello.com/c/BGPZIAoa/1745-format-review-orthographywritingsystem)
