### ISSUE TITLE
Sense.baseCategory

### ISSUE THREAD

**Issue by dwhieb** [digitallinguistics/spec#399]
### Problem
`Lexeme.category` says that, for grammatical morphemes, this should be used to describe the category of the item that the affix attaches to. This is unintuitive and confusing.

### Solution
Add a `Sense.baseCategory` property, which indicates the category of the item that an affix attaches to. This would generally (but not obligatorily) be used in tandem with the `Sense.derives` property.

In the case of grammatical affixes, the `category` property could be omitted.

**Comment by dwhieb** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[spec] Sense.baseCategory](https://trello.com/c/FsfP0HLb/90-spec-sensebasecategory)

**Comment by vadekh** [comment]
@dwhieb does this property replace Sense.category? If not, does the Sense.category description need to be updated?

**Comment by dwhieb** [comment]
No it doesn't replace Sense.category, but yes Sense.category should be updated to clarify the adjusted use. I'll check out your PR now and make edits if it needs any.

**Comment by dwhieb** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[format] review: Sense 2.1](https://trello.com/c/gRqTGzx3/1747-format-review-sense-21)
